### ISSUE TITLE
Cookie warning about SameSite being None

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/dibs#9]
The bottle session plugin uses Cookies. In addition to setting the cookie name and duration we also should set the cookie_secure status. False should set hte SameSite status to Lax and True should set it to Secure based on the Python 3.8 http.cookie support.

This can be rolled out in the next refresh for dibs.caltechlibrary.dev after we get some feed back.

**Comment by mhucka** [comment]
I worked through what's needed to set this and tried to find a way to set it automatically based on whether the server is using https or not, but due to the sequence in which server.py and adapter.wsgi are loaded, the information isn't available at the time the session middleware is configured.  That would be changed but would require rethinking and rewriting what adapter.wsgi does. As an alternative, for now, I added a variable to settings.ini.  The change are in commit 728b0de.

**Comment by mhucka** [comment]
This is no longer an issue, as we don't use cookies at all anymore. I'm closing this, but @rsdoiel feel free to reopen if I'm wrong!

**Comment by rsdoiel** [comment]
You are correct, shib allowed us to be cookie-less. I especially miss the peanut cookies.

**Comment by mhucka** [comment]
Rather fond of chocolate chip myself, but to each his own!

**Comment by rsdoiel** [comment]
Chocolate chip are indeed very tasty and it was hard choice between peanut butter and chocolate chip. But in a world without cookies I can get the chocolate chip cookie experiences in sorta of brownie form (I prefer the chewy Chocolate chip over the dry crunchy ones) but the brownie version of peanut butter cookies doesn't really work.  Oh this world without cookies. ;-)
